### ISSUE TITLE
Unable to run the PKC-2019 experiments

### ISSUE THREAD

**Issue by lducas** [KULeuven-COSIC/PQCRYPTO-decryption-failures#1]
Dear Jan-Pieter,

I have tried running your scripts with both sage and python, but had troubles with imports in both cases. I did init and update the submodule for the LWEestimator, but still no dice

``` python
> sage secretestimation.py 
Traceback (most recent call last):
  File "secretestimation.py", line 11, in <module>
    from estimateLWE.estimates import para_cost_scheme, flatten
  File "/ufs/ducas/postdoc/LeakingLWE/Codes/PQCRYPTO-decryption-failures/DecryptionFailureAttack/estimateLWE/estimates.py", line 25, in <module>
    import estimator as est
ImportError: No module named estimator
/DecryptionFailureAttack 
```
 ``` python
> python secretestimation.py 
Traceback (most recent call last):
  File "secretestimation.py", line 11, in <module>
    from estimateLWE.estimates import para_cost_scheme, flatten
  File "/ufs/ducas/postdoc/LeakingLWE/Codes/PQCRYPTO-decryption-failures/DecryptionFailureAttack/estimateLWE/estimates.py", line 24, in <module>
    from sage.all import *
ImportError: No module named sage.all
```
I am using Fedora 30, Python 2.7.16 and sage 8.8.

**Comment by lducas** [comment]
I tried with the new instructions. Still failing, same message...

**Comment by lducas** [comment]
The given instructions are :
``` bash
git submodule update
cd estimateLWE
git submodule init
git submodule update
cd ..
```
but I got it to work with 
``` bash
git submodule update
cd estimateLWE
git submodule init
git submodule update
cd estimator
git submodule init
git submodule update
cd ../../
```

Thanks !

**Comment by danversjp** [comment]
Should be fixed now. Thanks for letting us know!
